name: ci
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BATON_TOKEN: ${{ secrets.BATON_TOKEN }}
      BATON_ORGS: ConductorOne
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-github
        run: go build ./cmd/baton-github
      - name: Grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v4
        with:
          connector: ./baton-github
          baton-entitlement: 'repository:642588514:admin'
          baton-principal: '166871869'
          baton-principal-type: 'user'
